add option to not zero out gradients and method to do it
davisking/dlib pull request #2477
Opened 2021-12-21 21:36 UTC by arrufat

So, as I mentioned in #2292, it can be useful, sometimes, to inspect the intermediate gradients in the network.
Notable use cases include computing things like [GradCAM](https://arxiv.org/abs/1610.02391), or cumulating the gradients before back propagation to use a larger batch size.

With this PR, you can do something like:
```c++
net.compute_loss(x, labels.begin());
net.back_propagate_error(x, false);  // the false here means "don't zero out gradients automatically"
const auto& gi = net.subnet().get_gradient_input();  // before this PR this would always be zero.
// do something wiith the gradients...
net.zero_out_gradients();  // zero out input gradients for next iteration
```
I've updated the `back_propagate_error` and `compute_parameter_gradients` to have an extra boolean defaulted to the current behavior. Maybe it should be an enum?
```c++
enum class should_zero_out_gradients : uint8_t
{
    yes,
    no
}
```

I would like to support those cases in dlib, and I have tried not to break the current API. What do you think? Am I close to something that might make it into dlib?

Maybe the name of the method should be more explicit? Like `zero_out_input_gradients`?

If that's OK, I will update the documentation.

2022-01-01 23:52 UTC, davisking requested changes
Yeah, seems sensible.  I like your `enum` `should_zero_out_gradients` idea too.  Totally do that instead of using a `bool` :)

2022-01-01 23:52 UTC, davisking commented on dlib/dnn/core.h
> +            x_grad = 0;
```suggestion
            gradient_input_is_stale = true;
```
This should do it and avoid unnecessary assignments when it's already 0.

2022-01-01 23:52 UTC, davisking commented on dlib/dnn/core.h
> +        void zero_out_gradients()
```suggestion
        void set_gradient_inputs_to_zero()
```
How about this name?

2022-01-02 19:29 UTC, arrufat commented
I think the `enum` name is a bit too long… maybe it's not an issue, but it would be nice to have a more compact name, and I can't think of a good one :(

2022-01-03 12:40 UTC, davisking commented
> should_zero_out_gradients

`zero_gradients::yes`?

2022-01-03 15:34 UTC, arrufat commented
If tests pass, I think it's ready for review :)

2022-01-05 13:21 UTC, davisking commented on dlib/dnn/core.h
> +            x_grad = 0;
```suggestion
            gradient_input_is_stale = true;
```
This works here too right?

2022-01-05 13:44 UTC, arrufat commented on dlib/dnn/core.h
> +            x_grad = 0;
Yes, right! Thank you.

2022-01-05 13:46 UTC, merged

2022-01-05 13:47 UTC, davisking commented
Sweet, thanks for the PR :)